version: 1.0.0.{build}

environment:
  configuration: Release

branches:
  except:
  - design

image: Visual Studio 2017

install:
- ps: |
    appveyor-retry choco install octopustools
    appveyor-retry dotnet restore .\Sloth.Api\
    appveyor-retry dotnet restore .\Sloth.Web\
    appveyor-retry dotnet restore .\Sloth.Jobs.CyberSource.BankReconcile\
    appveyor-retry dotnet restore .\Sloth.Jobs.Kfs.ScrubberUpload\

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'

build_script:
- ps: |
    dotnet build .\Sloth.Api\ --configuration $Env:configuration
    dotnet build .\Sloth.Web\ --configuration $Env:configuration
    dotnet build .\Sloth.Jobs.CyberSource.BankReconcile\ --configuration $Env:configuration
    dotnet build .\Sloth.Jobs.Kfs.ScrubberUpload\ --configuration $Env:configuration

after_build:
- ps: |
    dotnet publish .\Sloth.Api\ --output .\publish --configuration $Env:configuration
    octo pack --id Sloth.Api --version $Env:APPVEYOR_BUILD_VERSION --releaseNotes $Env:APPVEYOR_REPO_COMMIT_MESSAGE --basepath .\Sloth.Api\publish\ --outFolder .\artifacts\

    dotnet publish .\Sloth.Web\ --output .\publish --configuration $Env:configuration
    octo pack --id Sloth.Web --version $Env:APPVEYOR_BUILD_VERSION --releaseNotes $Env:APPVEYOR_REPO_COMMIT_MESSAGE --basepath .\Sloth.Web\publish\ --outFolder .\artifacts\

    dotnet pack .\Sloth.Jobs.CyberSource.BankReconcile\ --no-build --output ..\artifacts /p:PackageVersion=$Env:APPVEYOR_BUILD_VERSION

    dotnet pack .\Sloth.Jobs.Kfs.ScrubberUpload\ --no-build --output ..\artifacts /p:PackageVersion=$Env:APPVEYOR_BUILD_VERSION


test_script:
- ps: dotnet test .\Sloth.Test\Sloth.Test.csproj

artifacts:
- path: artifacts\**\*.nupkg
  name: nugetweb

deploy:
- provider: NuGet
  server: https://scruffy.caes.ucdavis.edu/nuget/packages
  api_key:
    secure: eq+xgeyNzzar8kL7vAobzU06RSbnw8Hbw3wgFDgYTeo=
  skip_symbols: true
  on:
    branch: master

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: caes-development
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
