version: 1.0.0.{build}

environment:
  configuration: Release

branches:
  except:
  - design

image: Visual Studio 2017

install:
- ps: |
    appveyor-retry choco install octopustools
    appveyor-retry dotnet restore

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'

build_script:
- ps: dotnet build --configuration $Env:configuration

after_build:
- ps: |
    dotnet publish .\Sloth.Api\ --output ..\publish --configuration $Env:configuration
    octo pack --id Sloth.Api --version $Env:APPVEYOR_BUILD_VERSION --releaseNotes $Env:APPVEYOR_REPO_COMMIT_MESSAGE --basepath .\publish\ --outFolder .\artifacts\

test_script:
- ps: dotnet test .\Sloth.Test\Sloth.Test.csproj

artifacts:
- path: .\artifacts\Sloth.*.nupkg'
  name: nugetweb

deploy:
- provider: NuGet
  server: https://scruffy.caes.ucdavis.edu/nuget/packages
  api_key:
    secure: eq+xgeyNzzar8kL7vAobzU06RSbnw8Hbw3wgFDgYTeo=
  skip_symbols: true
  on:
    branch: master

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: caes-development
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
