version: 1.0.0.{build}

environment:
  configuration: Release

branches:
  except:
  - design

image: Visual Studio 2017

install:
- ps: appveyor-retry dotnet restore

cache:
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'

before_build:
- ps: |
    $path = (Get-Item .\Sloth.Api\Sloth.Api.csproj).FullName
    $csproj = [xml](Get-Content $path)
    $csproj.Project.PropertyGroup.Version = $Env:APPVEYOR_BUILD_VERSION
    $csproj.Project.PropertyGroup.PackageReleaseNotes = $Env:APPVEYOR_REPO_COMMIT_MESSAGE
    $csproj.Save($path)

build_script:
- ps: dotnet build --configuration %configuration%

after_build:
- ps: |
  dotnet publish .\Sloth.Api\ --output .\publish --configuration %configuration%
  octo pack --id Sloth.Api --version %APPVEYOR_BUILD_VERSION% --basepath .\publish\

test_script:
- ps: dotnet test .\Sloth.Test\Sloth.Test.csproj

artifacts:
- path: '**/bin/**/Sloth.*.nupkg'
  name: nugetweb

deploy:
- provider: NuGet
  server: https://scruffy.caes.ucdavis.edu/nuget/packages
  api_key:
    secure: eq+xgeyNzzar8kL7vAobzU06RSbnw8Hbw3wgFDgYTeo=
  skip_symbols: true
  on:
    branch: master

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: caes-development
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
