# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 4.9.x

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build Sloth.Api'
  inputs:
    command: 'build'
    projects: './sloth.api/sloth.api.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build Sloth.Web'
  inputs:
    command: 'build'
    projects: './sloth.web/sloth.web.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Assemble Sloth.Api'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    modifyOutputPath: false
    projects: './sloth.api/sloth.api.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/sloth.api'

- task: DotNetCoreCLI@2
  displayName: 'Assemble Sloth.Web'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    modifyOutputPath: false
    projects: './sloth.web/sloth.web.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/sloth.web'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'build'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: './sloth.test/sloth.test.csproj'
