// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sloth.Core;
using Sloth.Core.Models;
using System;

namespace Sloth.Core.Migrations
{
    [DbContext(typeof(SlothDbContext))]
    partial class SlothDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("Relational:Sequence:.KFS_Tracking_Number_Seq", "'KFS_Tracking_Number_Seq', '', '1', '1', '1', '9999999999', 'Int64', 'True'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sloth.Core.Models.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Issued");

                    b.Property<DateTime?>("Revoked");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Sloth.Core.Models.Integration", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DefaultAccount");

                    b.Property<string>("MerchantId");

                    b.Property<string>("ReportPasswordKey");

                    b.Property<string>("ReportUsername");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("Sloth.Core.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Sloth.Core.Models.Scrubber", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BatchDate");

                    b.Property<int>("BatchSequenceNumber");

                    b.Property<string>("Chart")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("Uri");

                    b.HasKey("Id");

                    b.ToTable("Scrubbers");
                });

            modelBuilder.Entity("Sloth.Core.Models.Team", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Sloth.Core.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatorId");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<string>("KfsTrackingNumber")
                        .HasMaxLength(10);

                    b.Property<string>("MerchantTrackingNumber");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("ProcessorTrackingNumber");

                    b.Property<string>("ScrubberId");

                    b.Property<int>("Status");

                    b.Property<DateTime>("TransactionDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ScrubberId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Sloth.Core.Models.Transfer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.Property<decimal>("Amount");

                    b.Property<string>("Chart")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<int>("Direction");

                    b.Property<int>("FiscalPeriod");

                    b.Property<int>("FiscalYear");

                    b.Property<string>("ObjectCode")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("ObjectType")
                        .HasMaxLength(2);

                    b.Property<string>("Project")
                        .HasMaxLength(10);

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(8);

                    b.Property<int>("SequenceNumber");

                    b.Property<string>("SubAccount")
                        .HasMaxLength(5);

                    b.Property<string>("SubObjectCode")
                        .HasMaxLength(3);

                    b.Property<string>("TransactionId");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("Sloth.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sloth.Core.Models.UserRole", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Sloth.Core.Models.UserTeam", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("TeamId");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("Sloth.Core.Models.ApiKey", b =>
                {
                    b.HasOne("Sloth.Core.Models.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Sloth.Core.Models.Transaction", b =>
                {
                    b.HasOne("Sloth.Core.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("Sloth.Core.Models.Scrubber", "Scrubber")
                        .WithMany("Transactions")
                        .HasForeignKey("ScrubberId");
                });

            modelBuilder.Entity("Sloth.Core.Models.Transfer", b =>
                {
                    b.HasOne("Sloth.Core.Models.Transaction", "Transaction")
                        .WithMany("Transfers")
                        .HasForeignKey("TransactionId");
                });

            modelBuilder.Entity("Sloth.Core.Models.UserRole", b =>
                {
                    b.HasOne("Sloth.Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sloth.Core.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sloth.Core.Models.UserTeam", b =>
                {
                    b.HasOne("Sloth.Core.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sloth.Core.Models.User", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
